### ISSUE TITLE
charging for transactions that didn't happen/ not managing assets

### ISSUE THREAD

**Issue by renatachebel** [hicetnunc2000/hicetnunc#257]
i haven't been able to manage my assets.
and every time i click on it, it just opens my creations page, and when i click on the objkt, the options to swap, cancel or burn do not appear. then i click on the circle and it opens my wallet. i confirm, and nothing. refresh, nothing. but it is charging me for all these operations, like, charging just to open the wallet! so far it has charged me over 0.1 xtz for not doing anything, not even opening the manage assets page! i filmed my screen to show this happening in case you want to see it.

**Comment by PureSpider** [comment]
The circle uses hDAO to promote your OBJKT into the hDAO stream.

Click on the OBJKT and then on your address or "sync" in the top right corner - then the tabs should appear.

**Comment by renatachebel** [comment]
right, had no idea i was gonna be charged for clicking on that button. good to know!
but i'm still having issues. it works for other objkts but not for this one: https://www.hicetnunc.xyz/objkt/9318
it's also weird that although i have an older objkt, but this one is showing before it in the timeline of my creations.

**Comment by renatachebel** [comment]
also, it's charging me in tezos and not in hdao although i have it.

**Comment by PureSpider** [comment]
It charges tezos for doing the transaction of using hDAO to promote your OBJKT into the hDAO stream

**Comment by renatachebel** [comment]
right. and why can't i manage that objkt? any clue?

**Comment by PureSpider** [comment]
Sadly, no idea 😞

**Comment by renatachebel** [comment]
oh </3 thank you for the answers though.

**Comment by crzypatchwork** [comment]
hopefully those issues were fixed today?

**Comment by Quasimondo** [comment]
I think we should add a rollover text to those circle buttons that give a hint what happens when you click them. Something like "Promote this work to the feed for 1 hDAO" (or whatever the correct value is)

**Comment by skenaja** [comment]
They should probably also be hidden or disabled if you've not got any hDAO

**Comment by renatachebel** [comment]
i've already sent the piece to the burn address but it still shows the duplicate on my page. so frustrating. tried burning it again today from the menu and it showed "burning..." for two hours and nothing. :(

**Comment by Quasimondo** [comment]
Yes that is still a bit of an annoying UI bug, I thought there was already an issue opened on this, but it looks like there is not - I will open one.

**Comment by Quasimondo** [comment]
Here you are: #265
